{% set name = "vertica-python" %}
{% set version = "1.3.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/vertica-python-{{ version }}.tar.gz
  sha256: 2b3bc970147a05cfb3e88026274291f3c69240c8d1c75522952dbca01bfd9d31

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip

  run:
    - python >=3.7
    - python-dateutil >=1.5
    - six >=1.10.0

test:
  imports:
    - vertica_python
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/vertica/vertica-python
  license_file: LICENSE
  license: Apache-2.0
  summary: Official native Python client for the Vertica Analytics Database.

extra:
  recipe-maintainers:
    - vertica-cla
    - sitingren
    - pmlandwehr
