{% set name = "vertica-python" %}
{% set version = "1.0.3" %}
{% set bundle = "tar.gz" %}
{% set hash = "cfe1794c5ba9fdfbd470a55d82f60c2e08e129828367753bf64199a58a539bc2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  sha256: {{ hash }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python
    - pip

  run:
    - python
    - python-dateutil >=1.5
    - pytz
    - future
    - six >=1.10.0
    - psycopg2 >=2.5.1

test:
  imports:
    - vertica_python
    - vertica_python.tests
    - vertica_python.vertica
    - vertica_python.vertica.messages
    - vertica_python.vertica.messages.backend_messages
    - vertica_python.vertica.messages.frontend_messages

about:
  home: https://github.com/uber/vertica-python/
  license_file: LICENSE
  license: MIT
  license_family: MIT
  summary: A native Python client for the Vertica database.
  dev_url: https://github.com/uber/vertica-python/

extra:
  recipe-maintainers:
    - pmlandwehr
